# You find the full pre-commit-tools docs here:
# https://pre-commit.com/

repos:
  - repo: https://github.com/rtts/djhtml
    rev: v1.5.2  # replace with the latest tag on GitHub
    hooks:
      - id: djhtml
        # Indent only HTML files in template directories
        files: .*/templates/.*\.html$
      - id: djcss
        entry: djcss -i --tabwidth 4
        # Run this hook only on SCSS files (CSS and SCSS is the default)
        types: [ scss ]
      - id: djjs
        # Exclude JavaScript files in vendor directories
        exclude: .*/node_modules/.*
